name: Continuous Deployment
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      # Build and test
      - name: Clean Install Packages
        run: npm ci
      - name: Build Site
        run: npm run build

      # Create artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: webpage
          path: public

  # Deploy
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: webpage
          path: public
      - name: Push to GitHub Pages branch
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: public
          github_token: ${{ secrets.GITHUB_TOKEN }}